### ISSUE TITLE
Cleaning up the homepage

### ISSUE THREAD

**Issue by shadowlion** [DancesportSoftware/das-frontend#136]
I took a look at the current iteration, and noted the following:

- [x] on mobile, the image for the logo shouldn't take up so much space, but I think it's because we have a fixed width on the image.

- [x] the Hero section for the logo should also lose its padding when on mobile - save some space, save some cats!

- [x] font-pair can be standardized. I'm gonna ask my designer intern for more info on this, since this is her specialty.

- [x] "in development" caption could turn into a badge, just like the MIT one below.

- [x] I've been thinking about this one for a while, but I believe our icons for the 3-item feature row isn't good enough to warrant an icon - I think the explanation is fine, but unless we have something better, i think we should remove them for now.

- [x] The github link for access to the repo takes you to the backend repo. I think it should change to the frontend instead

- [x] contribution option icons look a little too big

- [x] on the `/about` route, authors should have their names links to github. Or LinkedIn.

- [x] "Get Started" button should have a different color, one that adheres to better color pairing.

**Comment by shadowlion** [comment]
resolved with #137
