### ISSUE TITLE
Account Role Component

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das-frontend#73]
In  `pages`, create a component `role.vue` under `pages/u/account`.

There are 3 major sub-components:
- [x] A `+ New Role Application` which opens a modal/dialog for filing a new role application. Details of this modal/dialog will be given in a separated issue.
- [x]  A list view of roles that the user currently have access to. This can be obtained by `GET /api/v1.0/account/preference`. 
- [x] A list view of submitted role applications. Details of this component will be given in a separate issue.

**Comment by yubing24** [comment]
Implementation is complete as of last commit.
