### ISSUE TITLE
Admin UI: User Management Component

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das-frontend#75]
Create a User Management component to allow admin user to view user account details.

Route: `/u/admin/users`

Functions:
- [ ] Search users by:
  - [ ] First Name
  - [ ] Last Name
  - [ ] Role
  - [ ] Email
  - [ ] Phone Number
- [ ] View user account details:
  - [ ] Roles associated with this account
  - [ ] Email and phone number 

API Endpoint: `GET /api/v1.0/admin/account/search`
